---
galaxy_info:
  description: DoSomething.org Quantum Platfrom Base Setup
  company: DoSomething.org
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies: []
