- name: Add Jenkins Repo Key
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key id=D50582E6

- name: Add Jenkins Repo
  apt_repository: >
     repo='deb http://pkg.jenkins-ci.org/debian binary/'
     state=present 
     update_cache=yes

- name: Install Jenkins
  apt: name=jenkins state=present update_cache=yes
  notify: restart jenkins
