version: 2

models:
  - name: stg_typeform_nps_web
    description: A table containing the refreshed nps survey results from web users from 2021 onwards
    columns:
        - name: survey_response_id
          description: '{{ doc("survey_response_id") }}'
        - name: nps_score
          description: '{{ doc("nps_score") }}'
        - name: nps_reason
          description: '{{ doc("nps_reason") }}'
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: surveyed_on_url
          description: '{{ doc("surveyed_on_url") }}'
        - name: created_at
          description: '{{ doc("created_at") }}'
