version: 2

models:
  - name: bertly_clicks
    description: Table containing data from Bertly, our serverless link shortener.

    columns:
        - name: click_id
          description: '{{ doc("click_id") }}'

        - name: click_time
          description: '{{ doc("click_time") }}'

        - name: shortened
          description: '{{ doc("shortened") }}'

        - name: target_url
          description: '{{ doc("target_url") }}'

        - name: user_agent
          description: '{{ doc("browser_size") }}'

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: broadcast_id
          description: '{{ doc("broadcast_id") }}'

        - name: source
          description: '{{ doc("source") }}'

        - name: interaction_type
          description: '{{ doc("interaction_type") }}'
