version: 2

models:
  - name: email_subscription_topics_raw
    description: Table containing data for all member events. 

    columns:

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: newsletter_updated_at
          description: '{{ doc("updated_at") }}'

        - name: newsletter_topic
          description: '{{ doc("newsletter_topic") }}'

  - name: user_newsletter_subscriptions
    description: Table containing data for all member events. 

    columns:

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: newsletter_topic
          description: '{{ doc("newsletter_topic") }}'

        - name: topic_subscribed_at
          description: Timestamp when user subscribed to the newsletter topic

        - name: topic_unsubscribed_at
          description: Timestamp when user unsubscribed from the newsletter topic
