version: 2

models:
  - name: post_actions
    description: Table that tracks actions like reportbacks, civic actions and scholarship entries.

    columns:
        - name: id
          description: '{{ doc("id") }}'

        - name: name
          description: Name of the action. (e.g. Huddle for Heroes Photo Reportback)

        - name: campaign_id
          description: '{{ doc("campaign_id") }}'

        - name: post_type
          description: '{{ doc("post_type") }}'

        - name: noun
          description: '{{ doc("noun") }}'

        - name: verb
          description: '{{ doc("verb") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: updated_at
          description: '{{ doc("updated_at") }}'

        - name: deleted_at
          description: '{{ doc("deleted_at") }}'

        - name: _fivetran_deleted
          description: '{{ doc("_fivetran_deleted") }}'

        - name: _fivetran_synced
          description: '{{ doc("_fivetran_synced") }}'

        - name: reportback
          description: '{{ doc("reportback") }}'

        - name: civic_action
          description: '{{ doc("civic_action") }}'

        - name: scholarship_entry
          description: '{{ doc("scholarship_entry") }}'

        - name: active
          description: '{{ doc("active") }}'

        - name: anonymous
          description: '{{ doc("anonymous") }}'

        - name: callpower_campaign_id
          description: '{{ doc("callpower_campaign_id") }}'

        - name: quiz
          description: '{{ doc("quiz") }}'

        - name: action_type
          description: '{{ doc("action_type") }}'

        - name: online
          description: '{{ doc("online") }}'

        - name: time_commitment
          description: '{{ doc("time_commitment") }}'

