version: 2

models:

  - name: stg_historical_nps_web
    description: A table containing nps survey results from web users from 2018-2020
    columns:
        - name: survey_response_id
          description: '{{ doc("survey_response_id") }}'
        - name: nps_score
          description: '{{ doc("nps_score") }}'
        - name: nps_reason
          description: '{{ doc("nps_reason") }}'
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: surveyed_on_url
          description: '{{ doc("surveyed_on_url") }}'
        - name: legacy_campaign_id
        - name: created_at
          description: '{{ doc("created_at") }}'
