version: 2

models:

  - name: stg_typeform_nps_web
    description: A table containing the refreshed nps survey results from web users from 2021 onwards
    columns:
        - name: survey_id
        - name: nps_score
        - name: nps_reason
        - name: northstar_id
        - name: surveyed_on_url
        - name: created_at

  - name: stg_historical_nps_web
    description: A table containing nps survey results from web users from 2018-2020
    columns:
        - name: survey_id
        - name: nps_score
        - name: nps_reason
        - name: northstar_id
        - name: surveyed_on_url
        - name: legacy_campaign_id
        - name: created_at
