version: 2

models:

  - name: fct_nps_web_responses
    description: A table containing all nps web responses from 2018 onwards
    columns:
        - name: survey_response_id
          description: '{{ doc("survey_response_id") }}'
        - name: nps_score
          description: '{{ doc("nps_score") }}'
        - name: nps_promoter_cat
          description: '{{ doc("nps_promoter_cat") }}'
        - name: nps_reason
          description: '{{ doc("nps_reason") }}'
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: surveyed_on_url
          description: '{{ doc("surveyed_on_url") }}'
        - name: legacy_campaign_id
        - name: created_at
          description: '{{ doc("created_at") }}'
