version: 2

sources:
  - name: cio
    schema: '{{ env_var("CIO_WEBHOOK_EVENTS_SCHEMA") }}'
    tables:
      - name: event_log
      - name: customer_event_old
      - name: email_sent_old
models:
  - name: customer_event_new
    description: Table containing Cio customer events, e.g. user_unsubscribe
    columns:
        - name: email_id
          description: TBD
            tests:
              - not_null
        - name: customer_id
          description: TBD
        - name: email_address
          description: TBD
        - name: template_id
          description: TBD
        - name: event_id
          description: TBD
            tests:
              - not_null
        - name: timestamp
          description: TBD
            tests:
              - not_null
        - name: event_type
          description: TBD
        - name: cio_campaign_id
          description: TBD
        - name: cio_campaign_name
          description: TBD
        - name: cio_campaign_type
          description: TBD
  - name: email_sent_new
    description: Table containing Cio email sent events
    columns:
        - name: email_id
          description: TBD
            tests:
              - not_null
        - name: customer_id
          description: TBD
        - name: email_address
          description: TBD
        - name: template_id
          description: TBD
        - name: subject
          description: TBD
        - name: event_id
          description: TBD
            tests:
              - not_null
        - name: timestamp
          description: TBD
            tests:
              - not_null
