version: 2

models:
  - name: cio_customer_event
    description: Table containing Cio customer events, e.g. user_unsubscribe.
    columns:
      - &email_id
        name: email_id
        description: Unique message id (each individual message sent from Customer.io has a different "email_id"); can also be found in the unsubscribe link URL
      - &customer_id
        name: customer_id
        description: user id (can be retrieved from the person profile). Only present if the person is still active (not included if the person has been deleted).
      - &email_address
        name: email_address
        description: "\"To\" email address"
      - &template_id
        name: template_id
        description: |
          internal attribute, each email inside a campaign can have multiple template ids depending on the changes made over time. You can view it in the UI by filtering for a specific email under Email Log. For example: https://fly.customer.io/env/51831/email_logs?campaign=139744&template=343216
      - &event_id
        name: event_id
        description: internal attribute; id associated with the email_type action
      - &timestamp
        name: timestamp
        description: date and time when the event took place in unix (seconds since epoch) format
      - name: event_type
        description: type of event ("email_drafted", "email_sent", etc.)
      - &cio_campaign_id
        name: cio_campaign_id
        description: refer to the transactional, segment-triggered or newsletter campaign that generated the email
      - &cio_campaign_name
        name: cio_campaign_name
        description: refer to the transactional, segment-triggered or newsletter campaign that generated the email
      - &cio_campaign_type
        name: cio_campaign_type
        description: TBD
      - &cio_message_id
        name: cio_message_id
        description: campaign email id; can be found in the campaign URL after emails/ (e.g. https://fly.customer.io/env/51831/v2/composer/emails/225039)
      - &cio_message_name
        name: cio_message_name
        description: the name of the campaign email
  - name: cio_email_events
    description: Table containing CIO email open, converted, bounced, and unsubscribed events
    columns:
      - *email_id
      - *customer_id
      - *email_address
      - *template_id
      - &subject
        name: subject
        description: email subject
      - &href
        name: href
        description: Only on "clicked" events, the fully rendered URL of the link that was clicked.
      - &link_id
        name: link_id
        description: Only on "clicked" events, the ID of the tracked link that was clicked.
      - *event_id
      - *timestamp
      - *cio_campaign_id
      - *cio_campaign_name
      - *cio_campaign_type
      - *cio_message_id
      - *cio_message_name
