version: 2

models:
  - name: member_event_log
    description: Table containing data for all member events. 

    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: timestamp
          description: '{{ doc("created_at") }}'

        - name: action_type
          description: '{{ doc("action_type") }}'

        - name: action_id
          description: '{{ doc("action_id") }}'

        - name: source
          description: '{{ doc("source") }}'

        - name: action_serial_id
          description: '{{ doc("action_serial_id") }}'

        - name: channel
          description: '{{ doc("channel") }}'

        - name: type
          description: Whether the user is new or returning

        - name: first_action_month
          description: '{{ doc("first_action_month") }}'

