version: 2

sources:
  - name: public_intermediate
    schema: public_intermediate
    tables:
      - name: contentful_metadata
  - name: rogue
    schema: '{{ env_var("FT_ROGUE") }}'
    tables:
      - name: campaigns
  - name: campaign_info_historical
    # TODO: switch to '{{ env_var("HISTORICAL_ANALYTICS_SCHEMA") }}'
    # once we move this table to the right schema
    schema: public
    tables:
      - name: '{{ env_var("CAMPAIGN_INFO_ASHES_SNAPSHOT") }}'

models:
  - name: campaign_info
    description: A table containing information about campaigns

    columns:
        - name: campaign_id
          description: '{{ doc("campaign_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_run_id
          description: '{{ doc("campaign_run_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_name
          description: '{{ doc("campaign_name") }}'

        - name: campaign_cause
          description: '{{ doc("campaign_cause") }}'
          tests:
              - not_null

        - name: campaign_run_start_date
          description: '{{ doc("campaign_run_start_date") }}'
          tests:
              - unique
              - not_null

        - name: campaign_run_end_date
          description: '{{ doc("campaign_run_end_date") }}'
          tests:
              - not_null

        - name: campaign_created_date
          description: '{{ doc("campaign_created_date") }}'
          tests:
              - not_null

        - name: campaign_node_id
          description: '{{ doc("campaign_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_node_id_title
          description: '{{ doc("campaign_node_id_title") }}'
          tests:
              - not_null

        - name: campaign_run_id_title
          description: '{{ doc("campaign_run_id_title") }}'
          tests:
              - not_null

        - name: campaign_action_type
          description: '{{ doc("campaign_action_type") }}'
          tests:
              - not_null

        - name: campaign_cause_type
          description: '{{ doc("campaign_cause_type") }}'
          tests:
              - not_null

        - name: campaign_noun
          description: '{{ doc("campaign_noun") }}'
          tests:
              - unique
              - not_null

        - name: campaign_verb
          description: '{{ doc("campaign_verb") }}'
          tests:
              - not_null

        - name: campaign_cta
          description: '{{ doc("campaign_cta") }}'
          tests:
              - not_null

  - name: campaign_info_international
    description: A table containing information about international campaigns

    columns:
        - name: campaign_id
          description: '{{ doc("campaign_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_name
          description: '{{ doc("campaign_name") }}'

        - name: campaign_node_id
          description: '{{ doc("campaign_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_node_id_title
          description: '{{ doc("campaign_node_id_title") }}'
          tests:
              - not_null

        - name: campaign_run_id
          description: '{{ doc("campaign_run_id") }}'
          tests:
              - unique
              - not_null

        - name: campaign_run_id_title
          description: '{{ doc("campaign_run_id_title") }}'
          tests:
              - not_null

        - name: campaign_type
          description: '{{ doc("campaign_cause_type") }}'
          tests:
              - not_null

        - name: campaign_language
          description: '{{ doc("campaign_language") }}'

        - name: campaign_run_start_date
          description: '{{ doc("campaign_run_start_date") }}'
          tests:
              - unique
              - not_null

        - name: campaign_run_end_date
          description: '{{ doc("campaign_run_end_date") }}'
          tests:
              - not_null

        - name: campaign_created_date
          description: '{{ doc("campaign_created_date") }}'
          tests:
              - not_null

        - name: campaign_noun
          description: '{{ doc("campaign_noun") }}'
          tests:
              - unique
              - not_null

        - name: campaign_verb
          description: '{{ doc("campaign_verb") }}'
          tests:
              - not_null

        - name: campaign_cause_type
          description: '{{ doc("campaign_cause_type") }}'
          tests:
              - not_null

        - name: campaign_cta
          description: '{{ doc("campaign_cta") }}'
          tests:
              - not_null

        - name: campaign_action_type
          description: '{{ doc("campaign_action_type") }}'
          tests:
              - not_null
