version: 2

sources:
  - name: gambit
    schema: '{{ env_var("FT_GAMBIT") }}'
    tables:
      - name: conversations
      - name: messages

models:
  - name: messages_flattened
    description: Messages which nested values have been flattened for easier querying.
    columns: &messages_columns
      - name: agent_id
        description: '{{ doc("agent_id") }}'
      - name: attachment_content_type
        description: '{{ doc("attachment_content_type") }}'
      - name: attachment_url
        description: If set, link to the picture sent by the member.
      - name: broadcast_id
        description: If set, this message was an outbound broadcast (when direction == 'outbound-api-send'), or the User's reply to an outbound broadcast (when direction == 'inbound')
      - name: campaign_id
        description: If set, holds a reference to the **last** campaign topic the member's conversation was in. This is useful to allow members to talk to Gambit and get quick responses (through Rivescript), without Gambit completely forgetting what state the member's interaction with a campaign topic was in. '{{ doc("campaign_id") }}'
      - name: conversation_id
        description: Conversation the Message belongs to.
      - name: created_at
        description: Message's created date.
      - name: direction
        description: Describes if the message is being received (inbound) or being sent (outbound-*).
      - name: message_id
        description: Unique identifier for a Message (MongoDB id).
      - name: macro
        description: "If set, this message is part of this macro's workflow. Example: subscription status updates, voting plan submission, aswering a multichoice broadcast, etc."
      - name: match
        description: Rivescript trigger matched by inbound text.
      - name: carrier_delivered_at
        description: Date when we received a delivery confirmation from the carrier.
      - name: carrier_failure_code
        description: Error code reported by the carrier (Only for outbound messages).
      - name: total_segments
        description: Number of chunks the message is broken into by the SMS API.
      - name: platform_message_id
        description: The Message identifier per platform.
      - name: template
        description: If set, template of outbound message sent (e.g. askQuantity, completedMenu).
      - name: text
        description: Body of the message.
      - name: topic
        description: '{{ doc("topic") }}'
      - name: user_id
        description: The Northstar id of the member.
  - name: gambit_messages_inbound
    description: Inbound messages.
    columns: *messages_columns
  - name: gambit_messages_outbound
    description: Outbound messages.
    columns: *messages_columns
