version: 2

models:
  - name: user_activity
    description: Table containing aggregated user activity data.

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: sms_status
          description: '{{ doc("sms_status") }}'

        - name: email_status
          description: '{{ doc("cio_status") }}'

        - name: num_signups
          description: '{{ doc("num_signups") }}'

        - name: most_recent_signup
          description: '{{ doc("most_recent_signup") }}'

        - name: num_rbs
          description: '{{ doc("num_rbs") }}'

        - name: total_quantity
          description: '{{ doc("total_quantity") }}'

        - name: most_recent_rb
          description: '{{ doc("most_recent_rb") }}'

        - name: first_rb
          description: '{{ doc("first_rb") }}'

        - name: avg_time_betw_rbs
          description: '{{ doc("avg_time_betw_rbs") }}'

        - name: avg_days_next_action_after_rb
          description: '{{ doc("avg_days_next_action_after_rb") }}'

        - name: days_to_next_action_after_last_rb
          description: '{{ doc("days_to_next_action_after_last_rb") }}'

        - name: most_recent_mam_action
          description: '{{ doc("most_recent_mam_action") }}'

        - name: most_recent_email_open
          description: '{{ doc("most_recent_email_open") }}'

        - name: most_recent_all_actions
          description: '{{ doc("most_recent_all_actions") }}'

        - name: last_action_is_rb
          description: '{{ doc("last_action_is_rb") }}'

        - name: days_since_last_action
          description: '{{ doc("days_since_last_action") }}'

        - name: time_to_first_rb
          description: '{{ doc("time_to_first_rb") }}'

        - name: sms_unsubscribed_at
          description: '{{ doc("email_unsubscribed_at") }}'

        - name: user_unsubscribed_at
          description: '{{ doc("user_unsubscribed_at") }}'

        - name: voter_reg_acquisition
          description: '{{ doc("voter_reg_acquisition") }}'

