version: 2

models:
  - name: ovrd_quiz_funnel
    description: Needs a description

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

        - name: journey_begin_ts
          description: '{{ doc("journey_begin_ts") }}'

        - name: page_visit
          description: '{{ doc("page_visit") }}'

        - name: click_join_us
          description: '{{ doc("click_join_us") }}'

        - name: authenticated
          description: '{{ doc("authenticated") }}'

        - name: click_start_registration
          description: '{{ doc("click_start_registration") }}'

        - name: clicked_get_started
          description: '{{ doc("clicked_get_started") }}'

        - name: registered
          description: '{{ doc("registered") }}' 

        - name: clicked_share_fb
          description: '{{ doc("clicked_share_fb") }}'

        - name: traffic_source
          description: '{{ doc("traffic_source") }}'

        - name: submitted_quiz
          description: '{{ doc("submitted_quiz") }}'

        - name: clicked_submit_photo
          description: '{{ doc("clicked_submit_photo") }}'

        - name: registered
          description: '{{ doc("registered") }}'

        - name: register_affirmation_then_quiz
          description: '{{ doc("register_affirmation_then_quiz") }}'

        - name: submit_quiz_register_affirmation
          description: '{{ doc("submit_quiz_register_affirmation") }}'

  - name: ovrd_creator_funnel
    description: Needs a description

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

        - name: journey_begin_ts
          description: '{{ doc("journey_begin_ts") }}'

        - name: latest_get_started_ts
          description: '{{ doc("latest_get_started_ts") }}'

        - name: latest_registered_ts
          description: '{{ doc("latest_registered_ts") }}'

        - name: page_visit
          description: '{{ doc("page_visit") }}'

        - name: click_join_us
          description: '{{ doc("click_join_us") }}'

        - name: authenticated
          description: '{{ doc("authenticated") }}'

        - name: click_start_registration
          description: '{{ doc("click_start_registration") }}'

        - name: clicked_get_started
          description: '{{ doc("clicked_get_started") }}'

        - name: registered
          description: '{{ doc("registered") }}' 

        - name: click_copy_link
          description: '{{ doc("click_copy_link") }}'

        - name: clicked_any_share
          description: '{{ doc("clicked_any_share") }}'

        - name: clicked_share_fb
          description: '{{ doc("clicked_share_fb") }}'

        - name: clicked_share_email
          description: '{{ doc("clicked_share_email") }}'

        - name: clicked_share_fb_msgr
          description: '{{ doc("clicked_share_fb_msgr") }}'

        - name: clicked_share_twitter
          description: '{{ doc("clicked_share_twitter") }}'

        - name: referrals_start
          description: '{{ doc("referrals_start") }}'

        - name: referrals_completed
          description: '{{ doc("referrals_completed") }}'

  - name: ovrd_recipient_funnel
    description: Needs a description

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: journey_begin_ts
          description: '{{ doc("journey_begin_ts") }}'

        - name: clicked_link
          description: '{{ doc("clicked_link") }}'

        - name: clicked_get_started
          description: '{{ doc("clicked_get_started") }}'

        - name: completed_registration
          description: '{{ doc("completed_registration") }}'

  - name: group
    description: Needs a description

    columns:
        - name: id
          description: '{{ doc("northstar_id") }}'

        - name: group_type_id
          description: '{{ doc("group_type_id") }}'

        - name: name
          description: '{{ doc("group_name") }}'

        - name: goal
          description: '{{ doc("goal") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: updated_at
          description: '{{ doc("updated_at") }}'

        - name: city
          description: '{{ doc("city") }}'

        - name: external_id
          description: '{{ doc("external_id") }}'

        - name: state
          description: '{{ doc("state") }}'

        - name: school_id
          description: '{{ doc("school_id") }}'

  - name: group_types
    description: Needs a description

    columns:
        - name: id
          description: '{{ doc("northstar_id") }}'

        - name: name
          description: '{{ doc("group_name") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: updated_at
          description: '{{ doc("updated_at") }}'

        - name: filter_by_state
          description: '{{ doc("filter_by_state") }}'
