version: 2

models:
  - name: device_northstar
    description: Get a list of User ID's mapped to Device ID's

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

  - name: ovrd_creator_funnel
    description: Needs a description

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

        - name: journey_begin_ts
          description: '{{ doc("journey_begin_ts") }}'

        - name: latest_get_started_ts
          description: '{{ doc("latest_get_started_ts") }}'

        - name: latest_registered_ts
          description: '{{ doc("latest_registered_ts") }}'

        - name: page_visit
          description: '{{ doc("page_visit") }}'

        - name: click_join_us
          description: '{{ doc("click_join_us") }}'

        - name: authenticated
          description: '{{ doc("authenticated") }}'

        - name: click_start_registration
          description: '{{ doc("click_start_registration") }}'

        - name: clicked_get_started
          description: '{{ doc("clicked_get_started") }}'

        - name: registered
          description: '{{ doc("registered") }}' 

        - name: click_copy_link
          description: '{{ doc("click_copy_link") }}'

        - name: clicked_any_share
          description: '{{ doc("clicked_any_share") }}'

        - name: clicked_share_fb
          description: '{{ doc("clicked_share_fb") }}'

        - name: clicked_share_email
          description: '{{ doc("clicked_share_email") }}'

        - name: clicked_share_fb_msgr
          description: '{{ doc("clicked_share_fb_msgr") }}'

        - name: clicked_share_twitter
          description: '{{ doc("clicked_share_twitter") }}'

        - name: referrals_start
          description: '{{ doc("referrals_start") }}'

        - name: referrals_completed
          description: '{{ doc("referrals_completed") }}'

  - name: ovrd_recipient_funnel
    description: Needs a description

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: journey_begin_ts
          description: '{{ doc("journey_begin_ts") }}'

        - name: clicked_link
          description: '{{ doc("clicked_link") }}'

        - name: clicked_get_started
          description: '{{ doc("clicked_get_started") }}'

        - name: completed_registration
          description: '{{ doc("completed_registration") }}'
