version: 2

models:
  - name: device_northstar
    description: Get a list of User ID's mapped to Device ID's

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null
