version: 2

sources:
  - name: northstar
    schema: '{{ env_var("NORTHSTAR_FT_SCHEMA") }}'
    tables:
      - name: users
  - name: rogue
    schema: '{{ env_var("FT_ROGUE") }}'
    tables:
      - name: posts
