
version: 2

sources:
  - name: bertly
    schema: '{{ env_var("BERTLY") }}'
    tables:
      - name: clicks

  - name: rogue
    schema: '{{ env_var("FT_ROGUE") }}'
    tables:
      - name: actions
      - name: campaigns
      - name: clubs
      - name: groups
      - name: group_types
      - name: posts
      - name: signups

  - name: campaign_info_historical
    # TODO: switch to '{{ env_var("HISTORICAL_ANALYTICS_SCHEMA") }}'
    # once we move this table to the right schema
    schema: public
    tables:
      - name: campaign_info_ashes_snapshot

  - name: public_intermediate
    schema: public_intermediate
    tables:
      - name: contentful_metadata_raw

  - name: cio
    schema: '{{ env_var("CIO_WEBHOOK_EVENTS_SCHEMA") }}'
    tables:
      - name: event_log

  - name: cio_historical
    schema: '{{ env_var("HISTORICAL_ANALYTICS_SCHEMA") }}'
    tables:
      - name: cio_customer_event
      - name: cio_email_events

  - name: gambit
    schema: '{{ env_var("FT_GAMBIT") }}'
    tables:
      - name: conversations
      - name: messages

  - name: northstar
    schema: '{{ env_var("NORTHSTAR_FT_SCHEMA") }}'
    tables:
      - name: northstar_users_snapshot
      - name: users

  - name: northstar_historical
    schema: '{{ env_var("HISTORICAL_ANALYTICS_SCHEMA") }}'
    tables:
      - name: users

  - name: web_events_historical
    schema: '{{ env_var("HISTORICAL_ANALYTICS_SCHEMA") }}'
    tables:
      - name: phoenix_events
      - name: phoenix_sessions

  - name: snowplow
    schema: '{{ env_var("FT_SNOWPLOW") }}'
    tables:
      - name: event
      - name: snowplow_event
      - name: ua_parser_context

  - name: tmc
    schema: '{{ env_var("TMC_USERS_MATCHED_SCHEMA") }}'
    tables:
      - name: tmc_users_matched

  - name: historical_survey
    schema: '{{ env_var("SURVEY_SCHEMA") }}'
    tables:
      - name: 2018_2020_raw_nps_typeform_web

  - name: gsheets
    schema: '{{ env_var("FT_GOOGLE_SHEETS_SCHEMA") }}'
    tables:
      - name: 2018_2020_raw_nps_typeform_web
