version: 2

sources:
  - name: rogue
    schema: '{{ env_var("FT_ROGUE") }}'
    tables:
      - name: actions
      - name: posts
      - name: signups

models:
  - name: posts
    description: A table containing information about posts

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - not_null

        - name: id
          description: '{{ doc("id") }}'

        - name: type
          description: '{{ doc("type") }}'

        - name: action
          description: '{{ doc("action") }}'

        - name: status
          description: '{{ doc("status") }}'

        - name: quantity
          description: '{{ doc("quantity") }}'

        - name: campaign_id
          description: '{{ doc("campaign_id") }}'

        - name: reportback_volume
          description: '{{ doc("reportback_volume") }}'

        - name: source
          description: '{{ doc("source") }}'

        - name: source_bucket
          description: '{{ doc("source_bucket") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: url
          description: '{{ doc("url") }}'

        - name: text
          description: '{{ doc("text") }}'

        - name: signup_id
          description: '{{ doc("signup_id") }}'

        - name: post_class
          description: '{{ doc("post_class") }}'

        - name: is_accepted
          description: '{{ doc("is_accepted") }}'

        - name: action_id
          description: '{{ doc("action_id") }}'

        - name: location
          description: '{{ doc("location") }}'

        - name: postal_code
          description: '{{ doc("postal_code") }}'

        - name: is_reportback
          description: '{{ doc("is_reportback") }}'

        - name: civic_action
          description: '{{ doc("civic_action") }}'

        - name: scholarship_entry
          description: '{{ doc("scholarship_entry") }}'

        - name: school_id
          description: '{{ doc("school_id") }}'

  - name: reportbacks
    description: A table containing information about reportbacks

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - not_null

        - name: post_id
          description: '{{ doc("id") }}'

        - name: signup_id
          description: '{{ doc("signup_id") }}'

        - name: campaign_id
          description: '{{ doc("campaign_id") }}'

        - name: post_action
          description: '{{ doc("action") }}'

        - name: post_type
          description: '{{ doc("type") }}'

        - name: post_status
          description: '{{ doc("status") }}'

        - name: post_class
          description: '{{ doc("post_class") }}'

        - name: post_created_at
          description: '{{ doc("created_at") }}'

        - name: post_source
          description: '{{ doc("source") }}'

        - name: post_source_bucket
          description: '{{ doc("source_bucket") }}'

        - name: reportback_volume
          description: '{{ doc("reportback_volume") }}'        

        - name: civic_action
          description: '{{ doc("civic_action") }}'

        - name: scholarship_entry
          description: '{{ doc("scholarship_entry") }}'

        - name: location
          description: '{{ doc("location") }}'

        - name: postal_code
          description: '{{ doc("postal_code") }}'

        - name: post_bucket
          description: Grouping to which a post belongs (e.g. photo_rbs, phone_calls, social)

  - name: rock_the_vote
    description: A table containing ingested Rock the Vote data

    columns:
        - name: post_id
          description: '{{ doc("id") }}'

        - name: tracking_source
          description: CSV string representing source of record (e.g. campaignID:822,campaignRunID:8171,source:web,source_details:STV_Affirmation) '{{ doc("source_details") }}'

        - name: started_registration
          description: When the user started registration. '{{ doc("created_at") }}'

        - name: finish_with_state
          description: Whether the user ?

        - name: status
          description: Status of the submission. (e.g. complete, rejected, step 1)

        - name: email
          description: '{{ doc("email") }}'

        - name: zip
          description: '{{ doc("postal_code") }}'

  - name: signups
    description: A table containing information about signups

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - not_null

        - name: id
          description: '{{ doc("id") }}'

        - name: campaign_id
          description: '{{ doc("campaign_id") }}'

        - name: campaign_run_id
          description: Defined in web events docs. Fix this.

        - name: why_participated
          description: '{{ doc("why_participated") }}'

        - name: source
          description: '{{ doc("source") }}'

        - name: details
          description: '{{ doc("details") }}'

        - name: source_bucket
          description: '{{ doc("source_bucket") }}'

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: source_details
          description: '{{ doc("source_details") }}'

        - name: utm_medium
          description: '{{ doc("utm_medium") }}'

        - name: utm_source
          description: '{{ doc("utm_source") }}'

        - name: utm_campaign
          description: '{{ doc("utm_campaign") }}'

  - name: turbovote
    description: A table containing information about Turbovote registrations

    columns:
        - name: post_id
          description: '{{ doc("id") }}'

        - name: hostname
          description: '{{ doc("host") }}'

        - name: referral-code
          description: "???"

        - name: partner-comms-opt-in
          description: "???"

        - name: created_at
          description: '{{ doc("created_at") }}'

        - name: updated_at
          description: '{{ doc("updated_at") }}'

        - name: source_details
          description: '{{ doc("source_details") }}'

        - name: voter-registration-status
          description: Status of the voter's registration.

        - name: voter-registration-source
          description: Source of the registration.

        - name: voter-registration-method
          description: Method of registration.

        - name: voter-registration-preference
          description: Preference of registration.

        - name: email subscribed
          description: Whether the use is subscribed to email

        - name: sms subscribed
          description: Whether the use is subscribed to SMS

  - name: first_and_second_signups
    description: A table that brings signups 1 & 2 (of the same user) into a single row along with previously generated campaign-level data. The goal is comparing them to determine whether there are patterns corresponding to better report-back rates.
    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: campaign_id_1
          description: '{{ doc("campaign_id") }} for Signup #1'
        - name: campaign_id_2
          description: '{{ doc("campaign_id") }} for Signup #2'
        - name: signup_id_1
          description: '{{ doc("signup_id") }} #1'
        - name: signup_id_2
          description: '{{ doc("signup_id") }} #2'

        - name: signup_source_bucket_1
          description: '{{ doc("signup_source_bucket") }} for the first Signup'
        - name: signup_source_bucket_2
          description: '{{ doc("signup_source_bucket") }} for the second Signup'
        - name: signup_source_bucket_pattern
          description: 'Source Bucket pattern for both Signups e.g. (Both are Unknown, [sms|web|voter-reg|niche|Unknown / sms|web|voter-reg|niche|Unknown])'

        - name: campaign_action_type_1
          description: '{{ doc("campaign_action_type") }} for the first Signup'
        - name: campaign_action_type_2
          description: '{{ doc("campaign_action_type") }} for the second Signup'
        - name: campaign_action_type_pattern
          description: 'Campaign Action Type {{ doc("comparison_patterns") }}'

        - name: campaign_cause_type_1
          description: '{{ doc("campaign_cause_type") }} for the first Signup'
        - name: campaign_cause_type_2
          description: '{{ doc("campaign_cause_type") }} for the second Signup'
        - name: campaign_cause_type_pattern
          description: 'Campaign Cause Type {{ doc("comparison_patterns") }}'

        - name: campaign_online_offline_1
          description: Campaign for first Signup has (Online, Offline (IRL), or Both) types of Post Actions
        - name: campaign_online_offline_2
          description: Campaign for second Signup has (Online, Offline (IRL), or Both) types of Post Actions
        - name: campaign_online_offline_pattern
          description: 'Online Pattern (based on Post Actions) for the campaigns in both Signups e.g. (Both are Unknown, Both are [Both|Online|Offline|Unknown], [Both|Online|Offline|Unknown / Both|Online|Offline|Unknown])'

        - name: campaign_action_types_1
          description: '{{ doc("campaign_action_types") }} for the first Signup'
        - name: campaign_action_types_2
          description: '{{ doc("campaign_action_types") }} for the second Signup'
        - name: campaign_action_types_pattern
          description: 'Campaign Action Types {{ doc("comparison_patterns") }}'

        - name: campaign_scholarship_1
          description: Wether the Campaign for the first Signup is associated with a Scholarship -- if one of it's actions is setup as Scholarship Entry (e.g. Scholarship, Not Scholarship)
        - name: campaign_scholarship_2
          description: Wether the Campaign for the second Signup is associated with a Scholarship -- if one of it's actions is setup as Scholarship Entry (e.g. Scholarship, Not Scholarship)
        - name: campaign_scholarship_pattern
          description: 'Campaign Scholarship association pattern for both Signups e.g. (Both are Unknown, Both are [Scholarship|Not Scholarship|Unknown], [Scholarship|Not Scholarship|Unknown / Scholarship|Not Scholarship|Unknown])'

        - name: campaign_post_types_1
          description: '{{ doc("campaign_post_types") }} for the first Signup'
        - name: campaign_post_types_2
          description: '{{ doc("campaign_post_types") }} for the second Signup'
        - name: campaign_post_types_pattern
          description: 'Campaign Post Types {{ doc("comparison_patterns") }}'

        - name: num_rbs_1
          description: '{{ doc("num_rbs") }} for the first Signup'
        - name: num_rbs_2
          description: '{{ doc("num_rbs") }} for the second Signup'
        - name: num_rbs_pattern
          description: 'Num Reportbacks pattern for both Signups e.g. (No RB to Either SignUp, No RB to SignUp 1, No RB to SignUp 2, RB to Both SignUps)'

        - name: rb_source_buckets_1
          description: '{{ doc("post_source_buckets") }} for the first Signup'
        - name: rb_source_buckets_2
          description: '{{ doc("post_source_buckets") }} for the second Signup'
        - name: rb_source_buckets_pattern
          description: 'Post Sources pattern for both Signups e.g. (No RB to Either SignUp, [No RB|sms|web|sms , web|Unknown / No RB|sms|web|sms , web|Unknown])'

        - name: rb_post_types_1
          description: '{{ doc("post_types") }} for the first Signup'
        - name: rb_post_types_2
          description: '{{ doc("post_types") }} for the second Signup'
        - name: rb_post_types_pattern
          description: 'Post Types pattern for both Signups e.g. (No RB to Either SignUp, No RB to SignUp 1, No RB to SignUp 2, Both RB Post Types are Unknown, RB Post Type 1 is Unknown, RB Post Type 2 is Unknown, Same, Different)'

        - name: rb_online_offline_1
          description: '{{ doc("post_online_offline") }} for the first Signup'
        - name: rb_online_offline_2
          description: '{{ doc("post_online_offline") }} for the second Signup'
        - name: rb_online_offline_pattern
          description: 'Online/Offline posts pattern for both Signups e.g. (No RB to Either SignUp, No RB to SignUp 1, No RB to SignUp 2, Both RB Online/Offline are Unknown, RB Online/Offline 1 is Unknown, RB Online/Offline 2 is Unknown, Both are [Online|Offline|Online , Offline], [Online|Offline|Online , Offline|Unknown / Online|Offline|Online , Offline|Unknown])'

        - name: rb_action_types_1
          description: '{{ doc("post_action_types") }} for the first Signup'
        - name: rb_action_types_2
          description: '{{ doc("post_action_types") }} for the second Signup'
        - name: rb_action_types_pattern
          description: 'Post action types pattern for both Signups e.g. (No RB to Either SignUp, No RB to SignUp 1, No RB to SignUp 2, Both RB Action Types are Unknown, RB Action Type 1 is Unknown, RB Action Type 2 is Unknown, Same, Different)'
