version: 2

sources:
  - name: tmc
    schema: '{{ env_var("TMC_USERS_MATCHED_SCHEMA") }}'
    tables:
      - name: tmc_users_matched

models:
  - name: tmc_users_out
    description: A table containing latest user data for ingestion by The Movement Cooperative.

    columns:
        - name: first_name
          description: '{{ doc("first_name") }}'

        - name: last_name
          description: '{{ doc("last_name") }}'

        - name: address_street_1
          description: '{{ doc("address_street_1") }}'

        - name: address_street_2
          description: '{{ doc("address_street_2") }}'

        - name: city
          description: '{{ doc("city") }}'

        - name: state
          description: '{{ doc("state") }}'

        - name: zipcode
          description: '{{ doc("postal_code") }}'

        - name: mobile
          description: '{{ doc("mobile") }}'

        - name: email
          description: '{{ doc("email") }}'

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
