# This file specifically exists to generate DBT Docs for the
# GitHub Action dbt-docs to generate the DAG diagrams and 
# host them on GitHub. 
#
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile


default:
  outputs:
    docs:
    docs:
      type: postgres
      threads: 1
      host: "{{ env_var('PG_DOCS_HOST') }}"
      port: 5432
      user: "{{ env_var('PG_DOCS_USER') }}"
      pass: "{{ env_var('PG_DOCS_PASSWORD') }}"
      dbname: "{{ env_var('PG_DOCS_DATABASE') }}"
      schema: public
  target: docs
