version: 2

models:
  - name: snowplow_base_event
    description: Table that extracts and cleans up relevant columns from raw DS web click stream data.
    columns:
        - name: browser_size
          description: '{{ doc("browser_size") }}'
        - name: device_id
          description: '[Required] {{ doc("device_id") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_datetime
          description: '[Required] {{ doc("event_datetime") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_id
          description: '[Required] {{ doc("event_id") }}'
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: event_name
          description: '{{ doc("event_name") }}'
        - name: event_source
          description: '[Required] {{ doc("event_source") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_type
          description: '[Required] {{ doc("event_type") }}'
          tests:
            - not_null:
                severity: warn
        - name: host
          description: '[Required] {{ doc("host") }}'
          tests:
            - not_null:
                severity: warn
        - name: northstar_id
          description: '{{ doc("northstar_id") }} Unauthenticated visits will not have northstar id'
          tests:
            - relationships_distinct:
                to: ref('users')
                field: northstar_id
                severity: warn
        - name: path
          description: '[Required] {{ doc("path") }}'
          tests:
            - not_null:
                severity: warn
        - name: query_parameters
          description: '{{ doc("query_parameters") }}'
        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
        - name: referrer_source
          description: '{{ doc("referrer_source") }}'
        - name: se_action
          description: '{{ doc("se_action") }}'
        - name: se_category
          description: '{{ doc("se_category") }}'
        - name: se_label
          description: '{{ doc("se_label") }}'
        - name: session_counter
          description: '[Required] {{ doc("session_counter") }}'
          tests:
            - not_null:
                severity: warn
        - name: session_id
          description: '[Required] {{ doc("session_id") }}'
          tests:
            - not_null:
                severity: warn

  - name: snowplow_payload_event
    description: Table containing extra data from events in snowplow_base_event table
    columns:
        - name: block_id
          description: '{{ doc("block_id") }}'
        - name: campaign_id
          description: '{{ doc("internal_campaign_id") }}'
        - name: context_source
          description: '{{ doc("context_source") }}'
        - name: context_value
          description: '{{ doc("context_value") }}'
        - name: event_id
          description: '[Required] {{ doc("event_id") }}'
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: event_name
          description: '{{ doc("event_name") }}'
        - name: ft_timestamp
          description: '[Required] {{ doc("event_datetime") }}'
          tests:
            - not_null:
                severity: warn
        - name: group_id
          description: '{{ doc("group_id") }}'
        - name: modal_type
          description: '[Required conditionally] {{ doc("modal_type") }}'
          tests:
            - not_null_where:
                condition: "event_name similar to '%(opened_modal|closed_modal)%'"
                severity: warn
        - name: page_id
          description: '{{ doc("page_id") }}'
        - name: search_query
          description: '{{ doc("search_query") }}'
        - name: url
          description: '{{ doc("click_event_url") }}'
        - name: utm_campaign
          description: '{{ doc("utm_campaign") }}'
        - name: utm_medium
          description: '{{ doc("utm_medium") }}'
        - name: utm_source
          description: '{{ doc("utm_source") }}'

  - name: snowplow_raw_events
    description: Table combining snowplow_base_event and snowplow_payload_event into rich raw data source for all clickstream info
    columns:
        - name: block_id
          description: '{{ doc("block_id") }}'
        - name: browser_size
          description: '{{ doc("browser_size") }}'
        - name: campaign_id
          description: '{{ doc("internal_campaign_id") }}'
        - name: clicked_link_url
          description: '{{ doc("click_event_url") }}'
        - name: context_source
          description: '{{ doc("context_source") }}'
        - name: context_value
          description: '{{ doc("context_value") }}'
        - name: device_id
          description: '[Required] {{ doc("device_id") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_datetime
          description: '{{ doc("event_datetime") }}'
        - name: event_datetime
          description: '[Required] {{ doc("event_datetime") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_id
          description: '[Required] {{ doc("event_id") }}'
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: event_name
          description: '{{ doc("event_name") }}'
        - name: event_source
          description: '[Required] {{ doc("event_source") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_type
          description: '[Required] {{ doc("event_type") }}'
          tests:
            - not_null:
                severity: warn
        - name: group_id
          description: '{{ doc("group_id") }}'
        - name: host
          description: '[Required] {{ doc("host") }}'
          tests:
            - not_null:
                severity: warn
        - name: modal_type
          description: '[Required conditionally] {{ doc("modal_type") }}'
          tests:
            - not_null_where:
                condition: "event_name similar to '%(opened_modal|closed_modal)%'"
                severity: warn
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: page_id
          description: '{{ doc("page_id") }}'
        - name: path
          description: '[Required] {{ doc("path") }}'
          tests:
            - not_null:
                severity: warn
        - name: query_parameters
          description: '{{ doc("query_parameters") }}'
        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
        - name: referrer_source
          description: '{{ doc("referrer_source") }}'
        - name: se_action
          description: '[Required conditionally] {{ doc("se_action") }}'
          tests:
            - not_null_where:
                condition: "event_type = 'se'"
                severity: warn
        - name: se_category
          description: '[Required conditionally] {{ doc("se_category") }}'
          tests:
            - not_null_where:
                condition: "event_type = 'se'"
                severity: warn
        - name: se_label
          description: '{{ doc("se_label") }}'
        - name: search_query
          description: '{{ doc("search_query") }}'
        - name: session_counter
          description: '[Required] {{ doc("session_counter") }}'
          tests:
            - not_null:
                severity: warn
        - name: session_id
          description: '[Required] {{ doc("session_id") }}'
          tests:
            - not_null:
                severity: warn
        - name: utm_campaign
          description: '{{ doc("utm_campaign") }}'
        - name: utm_medium
          description: '{{ doc("utm_medium") }}'
        - name: utm_source
          description: '{{ doc("utm_source") }}'

  - name: snowplow_phoenix_events
    description: Table transforming snowplow_raw_event into rich derived data table for all clickstream info
    columns:
        - name: block_id
          description: '{{ doc("block_id") }}'
        - name: browser_size
          description: '{{ doc("browser_size") }}'
        - name: campaign_id
          description: '{{ doc("internal_campaign_id") }}'
        - name: campaign_name
          description: '{{ doc("campaign_name") }}'
        - name: clicked_link_url
          description: '{{ doc("click_event_url") }}'
        - name: context_source
          description: '{{ doc("context_source") }}'
        - name: context_value
          description: '{{ doc("context_value") }}'
        - name: device_id
          description: '[Required] {{ doc("device_id") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_datetime
          description: '[Required] {{ doc("event_datetime") }}'
          tests:
            - not_null:
                severity: warn
        - name: event_id
          description: '[Required] {{ doc("event_id") }}'
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: event_name
          description: '{{ doc("event_name") }}'
        - name: event_source
          description: '[Required] {{ doc("event_source") }}'
          tests:
            - not_null:
                severity: warn
        - name: group_id
          description: '{{ doc("group_id") }}'
        - name: host
          description: "URL domain"
        - name: modal_type
          description: '[Required conditionally] {{ doc("modal_type") }}'
          tests:
            - not_null_where:
                condition: "event_name similar to '%(opened_modal|closed_modal)%'"
                severity: warn
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
        - name: page_id
          description: '{{ doc("page_id") }}'
        - name: page_utm_campaign
          description: '{{ doc("utm_campaign") }}'
        - name: page_utm_medium
          description: '{{ doc("utm_medium") }}'
        - name: page_utm_source
          description: '{{ doc("utm_source") }}'
        - name: path
          description: '[Required] {{ doc("path") }}'
          tests:
            - not_null:
                severity: warn
        - name: query_parameters
          description: '{{ doc("query_parameters") }}'
        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
        - name: referrer_source
          description: '{{ doc("referrer_source") }}'
        - name: search_query
          description: '{{ doc("search_query") }}'
        - name: session_id
          description: '{{ doc("session_id") }}'

  - name: snowplow_sessions
    description: Table containing user session data derived from snowplow_phoenix_events
    columns:
        - name: session_id
          description: '{{ doc("session_id") }}'

        - name: event_id
          description: '{{ doc("event_id") }}'

        - name: device_id
          description: '{{ doc("device_id") }}'

        - name: landing_datetime
          description: '{{ doc("landing_datetime") }}'

        - name: ending_datetime
          description: '{{ doc("ending_datetime") }}'

        - name: session_duration_seconds
          description: '{{ doc("session_duration_seconds") }}'

        - name: num_pages_views
          description: '{{ doc("num_pages_views") }}'

        - name: landing_page
          description: '{{ doc("landing_page") }}'

        - name: exit_page
          description: '{{ doc("exit_page") }}'

        - name: days_since_last_session
          description: '{{ doc("days_since_last_session") }}'

  - name: phoenix_events_combined
    description: Table combining Snowplow based web event data with legacy Puck data based on 7/12/2019 cutover date
    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'

        - name: event_datetime
          description: '{{ doc("event_datetime") }}'

        - name: event_name
          description: '{{ doc("event_name") }}'

        - name: event_source
          description: '{{ doc("event_source") }}'

        - name: path
          description: '[Required] {{ doc("path") }}'
          tests:
            - not_null:
                severity: warn

        - name: host
          description: '{{ doc("host") }}'

        - name: query_parameters
          description: '{{ doc("query_parameters") }}'

        - name: clicked_link_url
          description: '{{ doc("click_event_url") }}'

        - name: page_utm_source
          description: '{{ doc("utm_source") }}'

        - name: page_utm_medium
          description: '{{ doc("utm_medium") }}'

        - name: page_utm_campaign
          description: '{{ doc("utm_campaign") }}'

        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
          tests:
              - not_null

        - name: referrer_path
          description: '{{ doc("referrer_path") }}'

        - name: referrer_source
          description: '{{ doc("referrer_source") }}'

        - name: campaign_id
          description: '{{ doc("internal_campaign_id") }}'

        - name: campaign_name
          description: '{{ doc("campaign_name") }}'

        - name: modal_type
          description: '[Required conditionally] {{ doc("modal_type") }}'
          tests:
            - not_null_where:
                condition: "event_name similar to '%(opened_modal|closed_modal)%'"
                severity: warn

        - name: session_id
          description: '{{ doc("session_id") }}'

        - name: browser_size
          description: '{{ doc("browser_size") }}'

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'

        - name: device_id
          description: '{{ doc("device_id") }}'

  - name: phoenix_sessions_combined
    description: Table combining Snowplow based web session data with legacy Puck data based on 7/12/2019 cutover date
    columns:
        - name: session_id
          description: '{{ doc("session_id") }}'

        - name: event_id
          description: '{{ doc("event_id") }}'

        - name: device_id
          description: '{{ doc("device_id") }}'

        - name: landing_datetime
          description: '{{ doc("landing_datetime") }}'

        - name: ending_datetime
          description: '{{ doc("ending_datetime") }}'

        - name: session_duration_seconds
          description: '{{ doc("session_duration_seconds") }}'

        - name: num_pages_views
          description: '{{ doc("num_pages_views") }}'

        - name: landing_page
          description: '{{ doc("landing_page") }}'

        - name: exit_page
          description: '{{ doc("exit_page") }}'

        - name: days_since_last_session
          description: '{{ doc("days_since_last_session") }}'
