version: 2

models:
  - name: snowplow_base_event
    description: Table that extracts and cleans up relevant columns from raw DS web clickstream data.

    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: event_source
          description: '{{ doc("event_source") }}'
          tests:
              - unique
              - not_null

        - name: event_datetime
          description: '{{ doc("event_datetime") }}'
          tests:
              - not_null

        - name: event_name
          description: '{{ doc("event_name") }}'

        - name: event_type
          description: '{{ doc("event_type") }}'
          tests:
              - not_null

        - name: host
          description: '{{ doc("host") }}'
          tests:
              - not_null
    
        - name: path
          description: '{{ doc("path") }}'
          tests:
              - not_null

        - name: query_parameters
          description: '{{ doc("query_parameters") }}'

        - name: se_category
          description: '{{ doc("se_category") }}'
    
        - name: se_action
          description: '{{ doc("se_action") }}'

        - name: se_label
          description: '{{ doc("se_label") }}'

        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - not_null
    
        - name: session_counter
          description: '{{ doc("session_counter") }}'
          tests:
              - not_null

        - name: browser_size
          description: '{{ doc("browser_size") }}'
          tests:
              - not_null

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null
    
        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
          tests:
              - not_null

        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
          tests:
              - not_null

        - name: referrer_source
          description: '{{ doc("referrer_source") }}'

  - name: snowplow_payload_event
    description: Table containing extra data from events in snowplow_base_event table
    columns:
        - name: block_id
          description: References specific content blocks from contentful CMS, PMs decide whether its important to send that info with specific click events.
        - name: campaign_id
          description: Internal campaign id from contentful. It will only be associated with specific events.
        - name: context_source
          description: TBD
        - name: context_value
          description: TBD
        - name: event_id
          description: '[Required] {{ doc("event_id") }}'
          tests:
            - unique:
                severity: warn
            - not_null:
                severity: warn
        - name: ft_timestamp
          description: '[Required] {{ doc("event_datetime") }}'
          tests:
            - not_null:
                severity: warn
        - name: group_id
          description: Unique identifier for groups. Group id is tied to work for volunteer credits and online voter drives (members can participate as part of a group)... product managers can choose to send web events with the group_id where its relevant. (right now it's being used for Online voter registration groups, but in the future it could be used for other types of group related efforts, e.g. volunteer hours).
        - name: modal_type
          description: '{{ doc("modal_type") }}'
        - name: page_id
          description: Unique identifier for the page. Technically optional, but would be good practice to send with all events (TODO).
        - name: search_query
          description: Term associated with any search events
        - name: url
          description: '[Required] {{ doc("url") }}'
        - name: utm_campaign
          description: '{{ doc("utm_campaign") }}'
        - name: utm_medium
          description: '{{ doc("utm_medium") }}'
        - name: utm_source
          description: '{{ doc("utm_source") }}'

  - name: snowplow_raw_events
    description: Table combining snowplow_base_event and snowplow_paylod_event into rich raw data source for all clickstream info

    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: event_source
          description: '{{ doc("event_source") }}'
          tests:
              - unique
              - not_null

        - name: event_datetime
          description: '{{ doc("event_datetime") }}'
          tests:
              - not_null

        - name: event_name
          description: '{{ doc("event_name") }}'

        - name: event_type
          description: '{{ doc("event_type") }}'
          tests:
              - not_null

        - name: host
          description: '{{ doc("host") }}'
          tests:
              - not_null
    
        - name: path
          description: '{{ doc("path") }}'
          tests:
              - not_null

        - name: query_parameters
          description: '{{ doc("query_parameters") }}'

        - name: se_category
          description: '{{ doc("se_category") }}'
    
        - name: se_action
          description: '{{ doc("se_action") }}'

        - name: se_label
          description: '{{ doc("se_label") }}'

        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - not_null
    
        - name: session_counter
          description: '{{ doc("session_counter") }}'
          tests:
              - not_null

        - name: browser_size
          description: '{{ doc("browser_size") }}'
          tests:
              - not_null

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null
    
        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
          tests:
              - not_null

        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
          tests:
              - not_null

        - name: referrer_source
          description: '{{ doc("referrer_source") }}'

        - name: utm_source
          description: '{{ doc("utm_source") }}'

        - name: utm_medium
          description: '{{ doc("utm_medium") }}'

        - name: utm_campaign
          description: '{{ doc("utm_campaign") }}'

        - name: clicked_link_url
          description: '{{ doc("url") }}'

        - name: campaign_id
          description: Internal campaign id from contentful

        - name: modal_type
          description: '{{ doc("modal_type") }}'

  - name: snowplow_phoenix_events
    description: Table transforming snowplow_raw_event into rich derived data table for all clickstream info

    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: event_datetime
          description: '{{ doc("event_datetime") }}'
          tests:
              - not_null

        - name: event_name
          description: '{{ doc("event_name") }}'

        - name: event_source
          description: '{{ doc("event_source") }}'
          tests:
              - unique
              - not_null

        - name: path
          description: "URL path"
          tests:
              - not_null

        - name: host
          description: "URL domain"
          tests:
              - not_null

        - name: query_parameters
          description: '{{ doc("query_parameters") }}'

        - name: clicked_link_url
          description: '{{ doc("url") }}'

        - name: page_utm_source
          description: '{{ doc("utm_source") }}'

        - name: page_utm_medium
          description: '{{ doc("utm_medium") }}'

        - name: page_utm_campaign
          description: '{{ doc("utm_campaign") }}'

        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
          tests:
              - not_null

        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
          tests:
              - not_null

        - name: referrer_source
          description: '{{ doc("referrer_source") }}'

        - name: campaign_id
          description: Internal campaign id from contentful

        - name: campaign_name
          description: "Name of campaign"

        - name: modal_type
          description: '{{ doc("modal_type") }}'

        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - not_null

        - name: browser_size
          description: '{{ doc("browser_size") }}'
          tests:
              - not_null

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

  - name: snowplow_sessions
    description: Table containing user session data derived from snowplow_phoenix_events

    columns:
        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - unique
              - not_null

        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

        - name: landing_datetime
          description: '{{ doc("landing_datetime") }}'
          tests:
              - not_null

        - name: ending_datetime
          description: '{{ doc("ending_datetime") }}'
          tests:
              - not_null

        - name: session_duration_seconds
          description: '{{ doc("session_duration_seconds") }}'
          tests:
              - not_null

        - name: num_pages_views
          description: '{{ doc("num_pages_views") }}'
          tests:
              - not_null

        - name: landing_page
          description: '{{ doc("landing_page") }}'
          tests:
              - not_null

        - name: exit_page
          description: '{{ doc("exit_page") }}'
          tests:
              - not_null

        - name: days_since_last_session
          description: '{{ doc("days_since_last_session") }}'

  - name: phoenix_events_combined
    description: Table combining Snowplow based web event data with legacy Puck data based on 7/12/2019 cutover date

    columns:
        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: event_datetime
          description: '{{ doc("event_datetime") }}'
          tests:
              - not_null

        - name: event_name
          description: '{{ doc("event_name") }}'

        - name: event_source
          description: '{{ doc("event_source") }}'
          tests:
              - unique
              - not_null

        - name: path
          description: '{{ doc("path") }}'
          tests:
              - not_null

        - name: host
          description: '{{ doc("host") }}'
          tests:
              - not_null
    
        - name: query_parameters
          description: '{{ doc("query_parameters") }}'

        - name: clicked_link_url
          description: '{{ doc("url") }}'

        - name: page_utm_source
          description: '{{ doc("utm_source") }}'

        - name: page_utm_medium
          description: '{{ doc("utm_medium") }}'

        - name: page_utm_campaign
          description: '{{ doc("utm_campaign") }}'

        - name: referrer_host
          description: '{{ doc("referrer_host") }}'
          tests:
              - not_null

        - name: referrer_path
          description: '{{ doc("referrer_path") }}'
          tests:
              - not_null

        - name: referrer_source
          description: '{{ doc("referrer_source") }}'

        - name: campaign_id
          description: Internal campaign id from contentful

        - name: campaign_name
          description: "Name of campaign"

        - name: modal_type
          description: '{{ doc("modal_type") }}'

        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - not_null

        - name: browser_size
          description: '{{ doc("browser_size") }}'
          tests:
              - not_null

        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

  - name: phoenix_sessions_combined
    description: Table combining Snowplow based web session data with legacy Puck data based on 7/12/2019 cutover date

    columns:
        - name: session_id
          description: '{{ doc("session_id") }}'
          tests:
              - unique
              - not_null

        - name: event_id
          description: '{{ doc("event_id") }}'
          tests:
              - unique
              - not_null

        - name: device_id
          description: '{{ doc("device_id") }}'
          tests:
              - not_null

        - name: landing_datetime
          description: '{{ doc("landing_datetime") }}'
          tests:
              - not_null

        - name: ending_datetime
          description: '{{ doc("ending_datetime") }}'
          tests:
              - not_null

        - name: session_duration_seconds
          description: '{{ doc("session_duration_seconds") }}'
          tests:
              - not_null

        - name: num_pages_views
          description: '{{ doc("num_pages_views") }}'
          tests:
              - not_null

        - name: landing_page
          description: '{{ doc("landing_page") }}'
          tests:
              - not_null

        - name: exit_page
          description: '{{ doc("exit_page") }}'
          tests:
              - not_null

        - name: days_since_last_session
          description: '{{ doc("days_since_last_session") }}'
