version: 2

models:
  - name: user_newsletter_signups
    description: Newsletter subscription status and signups for each northstar_id, for each month post 2019-03

    columns:
        - name: northstar_id
          description: '{{ doc("northstar_id") }}'
          tests:
              - relationships:
                  to: ref('users')
                  field: id

        - name: months_since_created
          description: '{{ doc("months_since_created") }}'
          tests:
              - not_null

        - name: last_mam
          description: '{{ doc("last_mam") }}'
          tests:
              - not_null
                        
        - name: period_start
          description: '{{ doc("period_start") }}'
          tests:
              - not_null
              
        - name: period_end
          description: '{{ doc("period_end") }}'
          tests:
              - not_null

        - name: newsletter_topic
          description: '{{ doc("newsletter_topic") }}'
          tests:
              - not_null

        - name: subscribed
          description: '{{ doc("subscribed_member") }}'
          
        - name: unsubscribed
          description: '{{ doc("unsubscribed") }}'
          
        - name: nl_status
          description: '{{ doc("nl_status") }}'
          
        - name: signup_source
          description: '{{ doc("signup_source") }}'
          
        - name: signup_date
          description: '{{ doc("signup_date") }}'
                                        
